<a href="https://colab.research.google.com/github/DeNerd1/Laboratory_5/blob/main/Exercise_5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 2 - Data manipulation and selection

In this problem you will clean the data from our data file by removing no-data values, convert temperature values in Fahrenheit to Celsius, and split the data into separate datasets using the weather station identification code. We will start this problem by cleaning and converting our temperature data. Please perform the tasks below by writing your code into the codeblocks in each section.


### Assesment

**Assesment will be based on following criteria:**

- Creating a new dataframe called `selected` that contains select columns from the data file
- Cleaning the new dataframe by removing no-data values
- Creating a new column for temperatures converted from Fahrenheit to Celsius
- Dividing the data into separate dataframes for the Station1 and Station2
- Saving the new dataframes to CSV files
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem


### Part 1

The first step for this problem is to read the data file `6153237444115dat.csv` again into a variable `data` using pandas. Remember to specify the no-data values (you can copy your code from assignment 1).

In [62]:
import pandas as pd
data = pd.read_csv("/content/sample_data/6153237444115dat.csv",na_values=['*', '**', '***', '****', '*****', '******'])
print(data)

# YOUR CODE HERE


        USAF   WBAN  YR--MODAHRMN    DIR   SPD   GUS   CLG  SKC   L   M  ...  \
0      28450  99999  201705010000  174.0  10.0  14.0   NaN  NaN NaN NaN  ...   
1      28450  99999  201705010020  180.0  10.0   NaN   4.0  NaN NaN NaN  ...   
2      28450  99999  201705010050  190.0  10.0   NaN   4.0  NaN NaN NaN  ...   
3      28450  99999  201705010100  188.0  12.0  16.0   NaN  NaN NaN NaN  ...   
4      28450  99999  201705010120  200.0  13.0   NaN   2.0  OBS NaN NaN  ...   
...      ...    ...           ...    ...   ...   ...   ...  ...  ..  ..  ...   
11689  29980  99999  201708311900  144.0  12.0  20.0  50.0  BKN NaN NaN  ...   
11690  29980  99999  201708312000  137.0  14.0  20.0  40.0  BKN NaN NaN  ...   
11691  29980  99999  201708312100  160.0  13.0   NaN   NaN  BKN NaN NaN  ...   
11692  29980  99999  201708312200  170.0  12.0  21.0  28.0  OVC NaN NaN  ...   
11693  29980  99999  201708312300  192.0  13.0  21.0  19.0  BKN NaN NaN  ...   

          SLP    ALT     STP  MAX  MIN 

Check that the first rows of the DataFrame look ok:

In [63]:
print(data.loc[0])

USAF                   28450
WBAN                   99999
YR--MODAHRMN    201705010000
DIR                    174.0
SPD                     10.0
GUS                     14.0
CLG                      NaN
SKC                      NaN
L                        NaN
M                        NaN
H                        NaN
VSB                      2.2
MW                       NaN
MW.1                     NaN
MW.2                     NaN
MW.3                     NaN
AW                      67.0
AW.1                     NaN
AW.2                     NaN
AW.3                     NaN
W                        8.0
TEMP                    31.0
DEWP                    31.0
SLP                   1009.2
ALT                      NaN
STP                    984.1
MAX                      NaN
MIN                      NaN
PCP01                    NaN
PCP06                    NaN
PCP24                    NaN
PCPXX                    NaN
SD                      35.0
Name: 0, dtype: object


Check the number of rows in the DataFrame:

In [64]:
print(len(data))

11694


### Part 2

Next, your task is to subset the data and remove rows with missing temperature values.

- Select the columns `USAF`, `YR--MODAHRMN`, `TEMP`, `MAX`, and `MIN` from the `data` dataframe and assign them to the variable `selected`
- Remove all rows from `selected` that have NoData in the column `TEMP` using the `dropna()` function

In [66]:
selected = data[["USAF","YR--MODAHRMN","TEMP","MAX","MIN"]].dropna()
# YOUR CODE HERE
print(selected)

        USAF  YR--MODAHRMN  TEMP   MAX   MIN
18     28450  201705010600  31.0  34.0  31.0
54     28450  201705011800  42.0  44.0  30.0
90     28450  201705020600  41.0  42.0  35.0
126    28450  201705021800  37.0  45.0  36.0
161    28450  201705030600  37.0  37.0  33.0
...      ...           ...   ...   ...   ...
11640  29980  201708291800  62.0  64.0  58.0
11652  29980  201708300600  60.0  62.0  59.0
11664  29980  201708301800  63.0  67.0  60.0
11676  29980  201708310600  61.0  63.0  59.0
11688  29980  201708311800  64.0  66.0  61.0

[485 rows x 5 columns]


Check that you selected the correct column names:

In [81]:
selected.head()

USAF  YR--MODAHRMN  TEMP   MAX   MIN  Celsius
18   28450  201705010600  31.0  34.0  31.0       -1
54   28450  201705011800  42.0  44.0  30.0        6
90   28450  201705020600  41.0  42.0  35.0        5
126  28450  201705021800  37.0  45.0  36.0        3
161  28450  201705030600  37.0  37.0  33.0        3

Check how many rows you have after removing the no-data values:

In [67]:
len(selected)

485

### Part 3

Next, you can convert the temperature values in Fahrenheit to Celsius.

- Create a new column in `selected` called `Celsius`
- Convert the Fahrenheit temperatures from `TEMP` using the conversion formula below and store the results in the new `Celsius` column.

$$
\Large
\begin{equation}
  T_{\mathrm{Celsius}} = (T_{\mathrm{Fahrenheit}} - 32)~/~1.8
\end{equation}
$$

- Round the values in the `Celsius` column to have 0 decimals (**do not** create a new column, update the current one)
- Convert the `Celsius` values into integers (**do not** create a new column, update the current one)

In [77]:
# YOUR CODE HERE
temp =[]
for temp_fah_ht in selected['TEMP']:
    temp_celius = (temp_fah_ht-32)/1.8
    temp.append(round(temp_celius))

selected['Celsius'] = temp
print(selected)



        USAF  YR--MODAHRMN  TEMP   MAX   MIN  Celsius
18     28450  201705010600  31.0  34.0  31.0       -1
54     28450  201705011800  42.0  44.0  30.0        6
90     28450  201705020600  41.0  42.0  35.0        5
126    28450  201705021800  37.0  45.0  36.0        3
161    28450  201705030600  37.0  37.0  33.0        3
...      ...           ...   ...   ...   ...      ...
11640  29980  201708291800  62.0  64.0  58.0       17
11652  29980  201708300600  60.0  62.0  59.0       16
11664  29980  201708301800  63.0  67.0  60.0       17
11676  29980  201708310600  61.0  63.0  59.0       16
11688  29980  201708311800  64.0  66.0  61.0       18

[485 rows x 6 columns]


In [82]:
# Check your dataframe
selected.head()

USAF  YR--MODAHRMN  TEMP   MAX   MIN  Celsius
18   28450  201705010600  31.0  34.0  31.0       -1
54   28450  201705011800  42.0  44.0  30.0        6
90   28450  201705020600  41.0  42.0  35.0        5
126  28450  201705021800  37.0  45.0  36.0        3
161  28450  201705030600  37.0  37.0  33.0        3

In [83]:
# Check data types
print(selected.dtypes)

USAF              int64
YR--MODAHRMN      int64
TEMP            float64
MAX             float64
MIN             float64
Celsius           int64
dtype: object


### Part 4

Your next task is to divide `selected` into two separate dataframes. Please use the given variable names and write your answer to the codeblock below.

- Select all rows from the `selected` DataFrame with the `USAF` code `29980` into a variable called `Station1`
- Select all rows from the `selected` DataFrame with the `USAF` code `28450` into a variable called `Station2`

In [94]:
Station1 = selected[selected['USAF'] == 29980]
Station2 = selected[selected['USAF'] == 28450]

# YOUR CODE HERE
print(Station1)
print(Station2)

        USAF  YR--MODAHRMN  TEMP   MAX   MIN  Celsius
8776   29980  201705010600  44.0  44.0  35.0        7
8788   29980  201705011800  48.0  54.0  43.0        9
8800   29980  201705020600  50.0  50.0  34.0       10
8812   29980  201705021800  53.0  61.0  49.0       12
8824   29980  201705030600  47.0  53.0  38.0        8
...      ...           ...   ...   ...   ...      ...
11640  29980  201708291800  62.0  64.0  58.0       17
11652  29980  201708300600  60.0  62.0  59.0       16
11664  29980  201708301800  63.0  67.0  60.0       17
11676  29980  201708310600  61.0  63.0  59.0       16
11688  29980  201708311800  64.0  66.0  61.0       18

[243 rows x 6 columns]
       USAF  YR--MODAHRMN  TEMP   MAX   MIN  Celsius
18    28450  201705010600  31.0  34.0  31.0       -1
54    28450  201705011800  42.0  44.0  30.0        6
90    28450  201705020600  41.0  42.0  35.0        5
126   28450  201705021800  37.0  45.0  36.0        3
161   28450  201705030600  37.0  37.0  33.0        3
...     ..

In [95]:
# Check the dataframe
print(f"Station1: \n{Station1.head()}\n")

Station1: 
       USAF  YR--MODAHRMN  TEMP   MAX   MIN  Celsius
8776  29980  201705010600  44.0  44.0  35.0        7
8788  29980  201705011800  48.0  54.0  43.0        9
8800  29980  201705020600  50.0  50.0  34.0       10
8812  29980  201705021800  53.0  61.0  49.0       12
8824  29980  201705030600  47.0  53.0  38.0        8



In [96]:
# Check the dataframe
print(f"Station2: \n{Station2.head()}\n")

Station2: 
      USAF  YR--MODAHRMN  TEMP   MAX   MIN  Celsius
18   28450  201705010600  31.0  34.0  31.0       -1
54   28450  201705011800  42.0  44.0  30.0        6
90   28450  201705020600  41.0  42.0  35.0        5
126  28450  201705021800  37.0  45.0  36.0        3
161  28450  201705030600  37.0  37.0  33.0        3



### Part 5

Now you can save your selections to csv files.

- Save the `Station1` DataFrame into the file `Station1.csv` (CSV format)
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Save the `Station2` DataFrame into the file `Station2.csv` (CSV format)
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers


In [102]:
# YOUR CODE HERE
Station1.to_csv("/content/sample_data/Station1.csv",index=False)
Station2.to_csv("/content/sample_data/Station2.csv",index=False)


### Assignment  2 summary

- Was anything unclear to you in Assignment 2?
- Did you encounter any problems?


Please write your answers and comments below.

Sources for the exercise : https://geo-python-site.readthedocs.io/en/latest/ running on a Attribution-ShareAlike 4.0 International Licence https://creativecommons.org/licenses/by-sa/4.0/deed.en